spring:
  profiles:
    active: marvelfitness

server:
  port: 5000
  
application:
  datasource:
    jdbc-url: jdbc:postgresql://marvelfitnessdb.czjsxitqqdv8.us-east-2.rds.amazonaws.com:5432/marvelfitness
    username: marvelfitness
    password: marvelfitness
    pool-size: 30
    
  